version: '2'

services: 
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=hbstudent
      - MYSQL_DATABASE=cinema_db
      - MYSQL_PASSWORD=hbstudent

  backend:
    image: spring-boot
    build:
      context: ./spring-boot
      dockerfile: ./Dockerfile.spring
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - CATALINA_OPTS=-Dspring.profiles.active=container
      - DATABASE_HOST=mysql
      - DATABASE_USER=hbstudent
      - DATABASE_PASSWORD=hbstudent
      - DATABASE_NAME=cinema_db 
      - DATABASE_PORT=3306

  frontend:
    image: angular
    build:
      context: ./angular
      dockerfile: ./Dockerfile.angular
    ports:
      - 4200:4200
